import numpy as np
from numpy.typing import NDArray

class SparseMatrix:
    def toarray(self) -> NDArray[np.float64]: ...

class TfidfVectorizer:
    def __init__(self, *, stop_words: str | None = None) -> None: ...
    def fit_transform(self, raw_documents: list[str]) -> SparseMatrix: ...
    def get_feature_names_out(self) -> NDArray[np.str_]: ...
