from typing import Any

class BaseTraceType: ...

class Scatter(BaseTraceType):
    def __init__(self, **kwargs: Any) -> None: ...

class Scatter3d(BaseTraceType):
    def __init__(self, **kwargs: Any) -> None: ...

class Figure:
    def __init__(self, data: list[BaseTraceType] | None = None, layout: dict[str, Any] | None = None) -> None: ...
    def update_layout(self, **kwargs: Any) -> Figure: ...
    def write_html(self, file: str, *, include_plotlyjs: bool | str = True, post_script: str | None = None) -> None: ...
