class BaseTraceType: ...

class Scatter(BaseTraceType):
    def __init__(self, **kwargs: object) -> None: ...

class Scatter3d(BaseTraceType):
    def __init__(self, **kwargs: object) -> None: ...

class Figure:
    def __init__(self, data: list[BaseTraceType]) -> None: ...
    def update_layout(self, **kwargs: object) -> Figure: ...
    def write_html(self, file: str, *, include_plotlyjs: bool | str = True, post_script: str | None = None) -> None: ...
